{{- if and (not .Values.awsS3.enabled) (not .Values.azure.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-volume
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.fileStorage.storageClassName }}
  storageClassName: {{ .Values.fileStorage.storageClassName }}
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.fileStorage.size }}
{{- end }}