---
apiVersion: v1
kind: Service
metadata:
  name: nx-cloud-frontend-service
  labels:
    app: nx-cloud-frontend
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
    app: nx-cloud-frontend
  ports:
    - port: 8080
      targetPort: 8080