{{ if not .Values.serviceAccount.enabled }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  name: nx-cloud
{{ end }}