global:
  nxCloudAppURL: "https://nx.test"
  mongodbConnectionString:
    secretName: nx-cloud-credentials
    secretKey: NX_CLOUD_MONGO_SERVER_ENDPOINT

extraObjects:
  appSecrets:
    apiVersion: v1
    kind: Secret
    metadata:
      name: nx-cloud-credentials
    type: Opaque
    stringData:
      VALKEY_PASSWORD: password
      NX_CLOUD_MONGO_SERVER_ENDPOINT: mongodb://mongo-mongodb-0.mongo-mongodb-headless.mongodb.svc.cluster.local:27017
      ADMIN_PASSWORD: password

  fileServerServiceAccount:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-file-server-sa

  aggregatorServiceAccount:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-aggregator-sa

  frontendServiceAccount:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-frontend-sa

  apiServiceAccount:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-api-sa

fileServer:
  enabled: true
  serviceAccount:
    create: false
    name: existing-file-server-sa
  deployment:
    resources: null

aggregator:
  serviceAccount:
    create: false
    name: existing-aggregator-sa
  cronjob:
    env:
      NX_CLOUD_SKIP_SLOW_AGGREGATOR_QUERIES: 'true'
      NX_CLOUD_LOG_OUTPUT_FORMAT: 'json'
    envValueFrom:
      ADMIN_PASSWORD:
        secretKeyRef:
          name: nx-cloud-credentials
          key: ADMIN_PASSWORD
    resources: null

frontend:
  serviceAccount:
    create: false
    name: existing-frontend-sa
  deployment:
    env:
      NX_API_INTERNAL_BASE_URL: 'http://nx-cloud-nx-api-service'
    envValueFrom:
      secretKeyRef:
        name: nx-cloud-credentials
        key: NX_CLOUD_MONGO_SERVER_ENDPOINT
    resources: null

api:
  serviceAccount:
    create: false
    name: existing-api-sa
  valkey:
    clientProvider: "redisson"
    useSentinel: true
    sentinelMasterName: "nxcloud"
    sentinelPort: 26379
    primaryAddress: valkey-node-0.valkey-headless.valkey.svc.cluster.local
    replicaAddresses: "valkey-node-1.valkey-headless.valkey.svc.cluster.local,valkey-node-2.valkey-headless.valkey.svc.cluster.local"
    port: 6379
    username: "default"
    passwordSecret:
      name: nx-cloud-credentials
      key: VALKEY_PASSWORD
  deployment:
    env:
      FILE_SERVER_INTERNAL_BASE_URL: http://nx-cloud-file-server-service
      FILE_SERVER_INTERNAL_PORT: "5000"
      ACTIVEMQ_ADDRESS: tcp://nx-cloud-messagequeue:61616
    resources: null
