global:
  nxCloudAppURL: "https://nx.test"

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: nx-cloud-credentials
    type: Opaque
    stringData:
      VALKEY_PASSWORD: password
      NX_CLOUD_MONGO_SERVER_ENDPOINT: mongodb://mongo-mongodb-0.mongo-mongodb-headless.mongodb.svc.cluster.local:27017
      ADMIN_PASSWORD: password

  # Service account for file-server
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-file-server-sa

  # Service account for aggregator
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-aggregator-sa

  # Service account for frontend
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-frontend-sa

  # Service account for api
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: existing-api-sa

fileServer:
  enabled: true
  serviceAccount:
    create: false
    name: existing-file-server-sa
  deployment:
    resources: null

aggregator:
  serviceAccount:
    create: false
    name: existing-aggregator-sa
  cronjob:
    env:
      NX_CLOUD_SKIP_SLOW_AGGREGATOR_QUERIES: 'true'
      NX_CLOUD_LOG_OUTPUT_FORMAT: 'json'
    envValueFrom:
      NX_CLOUD_MONGO_SERVER_ENDPOINT:
        secretKeyRef:
          name: nx-cloud-credentials
          key: NX_CLOUD_MONGO_SERVER_ENDPOINT
      ADMIN_PASSWORD:
        secretKeyRef:
          name: nx-cloud-credentials
          key: ADMIN_PASSWORD
    resources: null

frontend:
  serviceAccount:
    create: false
    name: existing-frontend-sa
  deployment:
    env:
      NX_API_INTERNAL_BASE_URL: 'http://nx-cloud-nx-api-service'
    envValueFrom:
      NX_CLOUD_MONGO_SERVER_ENDPOINT:
        secretKeyRef:
          name: nx-cloud-credentials
          key: NX_CLOUD_MONGO_SERVER_ENDPOINT
    resources: null

api:
  serviceAccount:
    create: false
    name: existing-api-sa
  deployment:
    env:
      FILE_SERVER_INTERNAL_BASE_URL: http://nx-cloud-file-server-service
      FILE_SERVER_INTERNAL_PORT: "5000"
      USE_VALKEY: "true"
      VALKEY_CLIENT_PROVIDER: redisson
      VALKEY_USE_SENTINEL: "true"
      VALKEY_SENTINEL_MASTER_NAME: "nxcloud"
      VALKEY_PRIMARY_ADDRESS: valkey-node-0.valkey-headless.valkey.svc.cluster.local
      VALKEY_REPLICA_ADDRESSES: "valkey-node-1.valkey-headless.valkey.svc.cluster.local,valkey-node-2.valkey-headless.valkey.svc.cluster.local"
      VALKEY_PORT: "6379"
      VALKEY_SENTINEL_PORT: "26379"
      VALKEY_USERNAME: "default"
      ACTIVEMQ_ADDRESS: tcp://nx-cloud-messagequeue:61616
    envValueFrom:
      NX_CLOUD_MONGO_SERVER_ENDPOINT:
        secretKeyRef:
          name: nx-cloud-credentials
          key: NX_CLOUD_MONGO_SERVER_ENDPOINT
      VALKEY_PASSWORD:
        secretKeyRef:
          name: nx-cloud-credentials
          key: VALKEY_PASSWORD
    resources: null
