global:
  imageTag: '2308.22.7'

nxCloudAppURL: 'URL_TO_ACCESS_INGRESS_FROM_DEV_MACHINES'

gitlab:
  mr:
    enabled: true
    apiUrl: 'https://api.example.com/'
    projectId: 'my-project'

secret:
  name: 'cloudsecret'
  nxCloudMongoServerEndpoint: 'NX_CLOUD_MONGO_SERVER_ENDPOINT'
  adminPassword: 'ADMIN_PASSWORD'
  gitlabAccessToken: 'GITLAB_ACCESS_TOKEN'

frontend:
  resources:
    requests:
      memory: '0.5Mi'
      cpu: '0.1'

nxApi:
  resources:
    requests:
      memory: '0.5Mi'
      cpu: '0.1'

fileServer:
  resources:
    requests:
      memory: '0.5Mi'
      cpu: '0.1'

aggregator:
  resources:
    requests:
      memory: '0.5Mi'
      cpu: '0.1'
