---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: cloud-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: '6.0.1'
  security:
    authentication:
      modes: [ 'SCRAM' ]
  users:
    - name: admin-user
      db: nrwl-api
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: admin-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      serviceName: cloud-mongodb-svc
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: encrypted-gp3
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: encrypted-gp3
            resources:
              requests:
                storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-password
type: Opaque
stringData:
  password: DB_PASSWORD
