apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: encrypted-gp3
parameters:
  fsType: ext4
  type: gp3
  encrypted: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer