{{- if .Values.enableMessageQueue }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.messagequeue.service.name }}
  labels:
    app: nx-cloud-messagequeue
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  selector:
    app: nx-cloud-messagequeue
  type: {{ .Values.messagequeue.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.messagequeue.service.port }}
      targetPort: {{ .Values.messagequeue.deployment.port }}
{{- end }}