---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nxApi.service.name }}
  labels:
    app: nx-cloud-nx-api
    {{- include "nxCloud.app.labels" . | indent 4 }}
  {{- if .Values.nxApi.service.annotations }}
  annotations:
      {{- toYaml .Values.nxApi.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nxApi.service.type }}
  selector:
    app: nx-cloud-nx-api
  ports:
    - port: {{ .Values.nxApi.service.port }}
      targetPort: {{ .Values.nxApi.deployment.port }}