apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-cloud-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nxCloud.mergedLabels" (dict "resourceLabels" .Values.frontend.deployment.labels "context" .) | nindent 4 }}
  {{- with .Values.frontend.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.frontend.hpa.enabled }}
  replicas: {{ .Values.frontend.deployment.replicas | default 1}}
  {{- end }}
  selector:
    matchLabels:
      app: nx-cloud-frontend
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  {{- with .Values.frontend.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "nxCloud.labels" . | nindent 8 }}
        app: nx-cloud-frontend
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.frontend.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.frontend.serviceAccount.create }}
      serviceAccountName: {{ .Values.frontend.serviceAccount.name }}
      {{- end }}
      {{- if or .Values.config.agentConfigs .Values.frontend.deployment.volumes }}
      volumes:
        {{- if .Values.config.agentConfigs }}
        - name: resource-class-config-volume
          configMap:
            name: agent-configuration
            items:
              - key: agentConfigs.yaml
                path: agentConfigs.yaml
        {{- end }}
        {{- if .Values.frontend.deployment.volumes }}
        {{- toYaml .Values.frontend.deployment.volumes | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.frontend.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nx-cloud-frontend
          image: {{ include "nxCloud.image" (dict "image" .Values.frontend.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default .Values.global.imagePullPolicy }}
          {{- if .Values.frontend.deployment.resources }}
          resources: {{- toYaml .Values.frontend.deployment.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 4202
          env:
            - name: NX_CLOUD_MODE
              value: {{ .Values.global.nxCloudMode | default "private-enterprise" | quote }}
            - name: NX_CLOUD_APP_URL
              value: {{ .Values.global.nxCloudAppURL }}
            - name: NX_API_INTERNAL_PORT
              value: {{ .Values.api.service.port | quote }}
            - name: NX_API_INTERNAL_BASE_URL
              value: http://{{ .Values.api.service.name }}
            {{- if .Values.config.agentConfigs }}
            - name: NX_CLOUD_RESOURCE_CLASS_FILEPATH
              value: /opt/nx-cloud/resource-classes/agentConfigs.yaml
            {{- end }}
            {{- if .Values.global.mongodbConnectionString.secretName }}
            - name: NX_CLOUD_MONGO_SERVER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mongodbConnectionString.secretName }}
                  key: {{ .Values.global.mongodbConnectionString.secretKey }}
            {{- end }}
            {{- if .Values.frontend.verboseLogging | default .Values.global.verboseLogging }}
            - name: NX_VERBOSE_LOGGING
              value: "true"
            {{- end }}
            - name: NX_API_LOG_LEVEL
              value: {{ .Values.frontend.logLevel | default .Values.global.logLevel | quote }}
            {{- range $key, $value := .Values.frontend.deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.frontend.deployment.envValueFrom }}
            - name: {{ $key }}
              valueFrom:
                {{- toYaml $value | nindent 16 }}
            {{- end }}
          {{- if .Values.frontend.deployment.envFrom }}
          envFrom:
            {{- toYaml .Values.frontend.deployment.envFrom | nindent 12 }}
          {{- end }}
          {{- if or .Values.frontend.deployment.volumeMounts .Values.config.agentConfigs }}
          volumeMounts:
            {{- if .Values.config.agentConfigs }}
            - name: resource-class-config-volume
              mountPath: /opt/nx-cloud/resource-classes
            {{- end }}
            {{- if .Values.frontend.deployment.volumeMounts }}
            {{- toYaml .Values.frontend.deployment.volumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.frontend.deployment.securityContext }}
          securityContext:
          {{- omit .Values.frontend.deployment.securityContext "fsGroup" "fsGroupChangePolicy" | toYaml | nindent 12 }}
          {{- end }}
        {{- with .Values.frontend.deployment.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
