{{- if .Values.frontend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nx-cloud-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nxCloud.mergedLabels" (dict "resourceLabels" .Values.frontend.hpa.labels "context" .) | nindent 4 }}
  {{- with .Values.frontend.hpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nx-cloud-frontend
  minReplicas: {{ .Values.frontend.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  {{- with .Values.frontend.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
  {{- if .Values.frontend.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.frontend.hpa.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- with .Values.frontend.hpa.customMetrics }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
